name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    uses: ./.github/workflows/tests.yml

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: Build wheel
        run: uv build --wheel

      - name: Publish to PyPI with uv
        env:
          UV_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish --token "$UV_PYPI_TOKEN"
